export {
  addHttpRemote,
  CONFIG_PATH,
  DEFAULT_REMOTE,
  type FetchFromHttpRemoteOptions,
  type FetchOutcome,
  fetchFromHttpRemote,
  fetchImplOf,
  type HttpRemote,
  httpRemoteUrl,
  InvalidRemoteNameError,
  InvalidRemoteUrlError,
  listHttpRemotes,
  type PushOutcome,
  type PushToHttpRemoteOptions,
  pushToHttpRemote,
  type RefPushOutcome,
  type RemoteCredentials,
  remoteCredentialsKey,
  remoteUrlKey,
  UnknownRemoteError,
} from "./http-remote.js";
