packages:
  - "packages/*"
  - "apps/*"

catalog:
  "@adobe/react-spectrum": ^3.47.0
  "@biomejs/biome": ^2.4.12
  "@hono/node-server": ^1.19.14
  "@internationalized/date": ^3.12.1
  "@react-stately/color": ^3.10.0
  "@spectrum-icons/workflow": ^4.3.0
  "@statewalker/shared-adapters": ^0.1.0
  "@statewalker/shared-baseclass": ^0.1.0
  "@statewalker/shared-intents": ^0.1.0
  "@statewalker/shared-registry": ^0.1.0
  "@statewalker/webrun-files": ^0.7.0
  "@statewalker/webrun-files-browser": ^0.7.1
  "@statewalker/webrun-files-mem": ^0.7.2
  "@tailwindcss/vite": ^4.2.2
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^4.7.0
  "@vitest/browser": ^4.1.4
  "@vitest/coverage-v8": ^4.1.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  hono: ^4.12.14
  htl: ^0.3.1
  import-meta-resolve: ^4.2.0
  jsdom: ^29.0.2
  lucide-react: ^1.8.0
  radix-ui: ^1.4.3
  react: ^19.2.5
  react-dom: ^19.2.5
  react-resizable-panels: ^4.10.0
  rimraf: ^6.1.3
  sucrase: ^3.35.1
  tailwind-merge: ^3.5.0
  tailwindcss: 4.2.2
  tsdown: ^0.21.9
  tsx: ^4.21.0
  turbo: ^2.9.6
  typescript: ^6.0.3
  vite: ^8.0.9
  vitest: ^4.1.4
  zod: ^4.3.6