import { IconRegistry } from "@statewalker/workbench-react/icons";
import {
  AlertCircle,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Copy,
  Edit,
  Eye,
  File,
  FileEdit,
  FileText,
  Folder,
  FolderOpen,
  Loader,
  MessageSquare,
  Moon,
  MoreHorizontal,
  Pencil,
  Plus,
  Search,
  Settings,
  Sun,
  Trash2,
  X,
} from "lucide-react";

export function createIconRegistry(): IconRegistry {
  const registry = new IconRegistry();
  registry.registerAll({
    "alert-circle": AlertCircle,
    check: Check,
    "check-circle": CheckCircle,
    "chevron-down": ChevronDown,
    "chevron-right": ChevronRight,
    circle: Circle,
    clock: Clock,
    copy: Copy,
    edit: Edit,
    eye: Eye,
    file: File,
    "file-edit": FileEdit,
    "file-text": FileText,
    folder: Folder,
    "folder-open": FolderOpen,
    loader: Loader,
    "message-square": MessageSquare,
    moon: Moon,
    "more-horizontal": MoreHorizontal,
    pencil: Pencil,
    plus: Plus,
    search: Search,
    settings: Settings,
    sun: Sun,
    "trash-2": Trash2,
    x: X,
  });
  return registry;
}
