import { A as s, C as i, D as t, a as n, K as o, T as l, b as g, c as u, g as w, d as V, e as b, f as r, h as c, i as p, l as M, j as T, k as h, m as D, n as P, p as x, o as A, q as C, r as k, s as y } from "./top-menu-view-Bzu4keoz.js";
export {
  s as ActivePanelView,
  i as ContextMenuRegistryView,
  t as DialogStackView,
  n as DockPanelView,
  o as KeyboardView,
  l as ToolbarView,
  g as TopMenuView,
  u as activatePanel,
  w as getActivePanelView,
  V as getContextMenuRegistryView,
  b as getDialogStackView,
  r as getKeyboardView,
  c as getToolbarView,
  p as getTopMenuView,
  M as listenContextMenu,
  T as listenDialog,
  h as listenMenu,
  D as listenPanel,
  P as listenToolbarAction,
  x as publishContextMenu,
  A as publishDialog,
  C as publishMenu,
  k as publishPanel,
  y as publishToolbarAction
};
